### ISSUE TITLE
Descendant combinator cannot be used after nth-child

### ISSUE THREAD

**Issue by simonkimi** [dint-dev/universal_html#60]
Hi! Thanks for your awsome package., but I encountered some problems in the following tests. Any ideas?

index.html
```html
<!DOCTYPE html>
<html lang="en">
<body>
<div id="root">
    <div>
        <p class="title">title1</p>
        <p class="content">p1</p>
    </div>
    <div>
        <p class="title">title2</p>
        <p class="content">p2</p>
    </div>
</div>
</body>
</html>
```

```dart
import 'dart:io';
import 'package:universal_html/parsing.dart';

void main() {
  final file = File('index.html').readAsStringSync();
  final document = parseHtmlDocument(file);

  print(document.body!.querySelector('#root div:nth-child(1)'));
  /*
  * <div>
        <p class="first">p1</p>
        <p class="second">p1</p>
    </div>*/


  print(document.body!.querySelector('#root div:nth-child(1)>.content'));
  /*
  * <p class="content">p1</p>*/


  print(document.body!.querySelector('#root div:nth-child(1) .content'));
  /*
  * Unhandled exception:
Null check operator used on a null value
#0      _matchesNthChildSelector (package:universal_html/src/html/dom/css_selectors.dart:65:37)
#1      _matchesSimpleSelector (package:universal_html/src/html/dom/css_selectors.dart:309:18)
#2      _matchesSelector (package:universal_html/src/html/dom/css_selectors.dart:148:8)
#3      _matchesSelector (package:universal_html/src/html/dom/css_selectors.dart:178:13)
#4      _matchesSelectorGroup (package:universal_html/src/html/dom/css_selectors.dart:242:9)
#5      _ElementOrDocument.querySelectorAll.<anonymous closure> (package:universal_html/src/html/dom/node.dart:763:11)
#6      _ElementOrDocument._forEachElementInTree (package:universal_html/src/html/dom/node.dart:787:10)
#7      _ElementOrDocument.querySelectorAll (package:universal_html/src/html/dom/node.dart:762:5)*/
}

```

**Comment by terrier989** [comment]
Thank you for the good issue report! 👍 This was fixed in 2.2.1.
